backend:
  name: git-gateway
  branch: main # GitHubのブランチ名（mainまたはmaster）

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "ブログ記事"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "カテゴリー", name: "category", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
